version: '3'

services:
  wordpress:
    image: wordpress:latest
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html/wp-content/themes/custom-theme
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root_password
    depends_on:
      - mysql

  mysql:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      MARIADB_DATABASE: wordpress
      MARIADB_ROOT_PASSWORD: root_password
    volumes:
      - ./src/data:/docker-entrypoint-initdb.d
      - mysql:/var/lib/mysql

volumes:
  mysql: